import Head from "next/head";
import Image from "next/image";
import "../styles/Home.module.css";
import { useState, useEffect } from "react";

import { Button } from "antd";

import Modal from "react-modal";
import { useAuth } from "../context/global";
import { diffcontext } from "../context/diff";
import {db} from "../firebase";
import { doc, setDoc, getDoc,collection,onSnapshot,orderBy,limit ,query} from "firebase/firestore";

export default function Home() {
  const [open, setOpen] = useState(false);

  const { logout, forgetPassword, currentUser, userinfo,products } = useAuth();
  const [isSSR, setIsSSR] = useState(true);

//console.log(products)

const [allproducts, setAllproducts] = useState([]);






useEffect(() => {
  onSnapshot(
    query(collection(db,"products"), orderBy("name", "desc")),
    (snapshot) => {
      const productsArr = snapshot.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
      }));
      setAllproducts(productsArr);
      console.log("All products is fetched", productsArr,'',allproducts);
    }
  );
}, []);







  useEffect(() => {
    setIsSSR(false);
    {
      /* { !isSSR &&  <NewList />} */
    }
  }, []);

  const sendtoemail = (e) => {
    e.preventDefault();
    const email = "maher9911133@gmail.com";
    forgetPassword(email);
  };

  return (
    <div className="  h-[200vh]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

{/* -------main sectin start- */}


<div>



{userinfo?.role}

{allproducts?.length}






</div>



    
    </div>
  );
}
